packages:
  - apps/*
  - packages/*

catalog:
  '@biomejs/biome': 2.3.13
  '@types/node': ^25
  dayjs: ^1.11.19
  typescript: ^5.9.3
  zod: ^4.3.6

onlyBuiltDependencies:
  - '@thallesp/nestjs-better-auth'
