import { validateEnvConfig } from '~/config/env.validation'

export default () =>
  validateEnvConfig({
    DATABASE_URL: process.env.DATABASE_URL,
    NODE_ENV: process.env.NODE_ENV,
    PORT: process.env.PORT,
    BREVO_API_KEY: process.env.BREVO_API_KEY,
    BREVO_API_URL: process.env.BREVO_API_URL,
    EMAIL_SENDER_NAME: process.env.EMAIL_SENDER_NAME,
    EMAIL_SENDER_EMAIL: process.env.EMAIL_SENDER_EMAIL,
    EMAIL_RECEIVER_EMAIL: process.env.EMAIL_RECEIVER_EMAIL,
    DEMARCHES_SIMPLIFIEES_URL: process.env.DEMARCHES_SIMPLIFIEES_URL,
    DEMARCHES_SIMPLIFIEES_TOKEN: process.env.DEMARCHES_SIMPLIFIEES_TOKEN,
    DEMARCHES_SIMPLIFIEES_DEMARCHE_ID: process.env.DEMARCHES_SIMPLIFIEES_DEMARCHE_ID,
    CLIENT_BASE_URL: process.env.CLIENT_BASE_URL,
    BREVO_EMAIL_VERIFICATION_TEMPLATE_ID: process.env.BREVO_EMAIL_VERIFICATION_TEMPLATE_ID,
    BREVO_PASSWORD_RESET_TEMPLATE_ID: process.env.BREVO_PASSWORD_RESET_TEMPLATE_ID,
    BREVO_IMPORT_USER_TEMPLATE_ID: process.env.BREVO_IMPORT_USER_TEMPLATE_ID,
    OAUTH_PROCONNECT_CLIENT_ID: process.env.OAUTH_PROCONNECT_CLIENT_ID,
    OAUTH_PROCONNECT_CLIENT_SECRET: process.env.OAUTH_PROCONNECT_CLIENT_SECRET,
    OAUTH_PROCONNECT_ISSUER: process.env.OAUTH_PROCONNECT_ISSUER,
    API_KEY_ENCRYPTION_SECRET: process.env.API_KEY_ENCRYPTION_SECRET,
  })
