'use client'

import { parseAsArrayOf, parseAsString, useQueryStates } from 'nuqs'
import { useEffect } from 'react'
import { buildEpciGroupName, parseUrbanismeDocType } from '~/utils/epci-group-name'

type UseEpciGroupNamePrefillArgs = {
  /** Libellé du territoire, construit par `buildTerritoryLabel`. Vide tant que l'EPCI de base n'est pas connu. */
  territoryLabel: string
  /** Nom du bassin d'habitat, quand le périmètre en est un : seul retenu pour nommer un SCoT. */
  bassinName?: string | null
}

/**
 * Propose un nom de groupe dérivé du territoire et, si l'utilisateur travaille sur un document
 * d'urbanisme, du type de document qu'il a désigné.
 *
 * Le nom proposé n'écrase jamais une saisie manuelle : `epciGroupNameAuto` marque dans l'URL que la
 * valeur courante a été générée. Passer par l'URL plutôt que par une ref permet de survivre au retour
 * depuis l'étape suivante, qui démonte le composant.
 */
export const useEpciGroupNamePrefill = ({ territoryLabel, bassinName }: UseEpciGroupNamePrefillArgs) => {
  const [{ epciGroupName, epciGroupNameAuto, urbanismeDoc, urbanismeDocType, urbanismeDocName }, setQueryStates] = useQueryStates({
    baseEpci: parseAsString,
    epcis: parseAsArrayOf(parseAsString).withDefault([]),
    epciGroupName: parseAsString,
    epciGroupNameAuto: parseAsString,
    urbanismeDoc: parseAsString,
    urbanismeDocType: parseAsString,
    urbanismeDocName: parseAsString,
  })

  const isAutoGenerated = !epciGroupName || epciGroupNameAuto === '1'
  const proposedName = territoryLabel
    ? buildEpciGroupName({
        bassinName,
        docName: urbanismeDocName,
        docType: parseUrbanismeDocType(urbanismeDocType),
        territoryLabel,
        worksOnUrbanismeDoc: urbanismeDoc === 'oui',
      })
    : ''

  useEffect(() => {
    if (!urbanismeDoc || !territoryLabel) return
    if (!isAutoGenerated) return
    if (proposedName === (epciGroupName ?? '')) return

    // « Autres » ne propose rien : le nom auto précédemment posé doit disparaître, pas persister.
    if (!proposedName) {
      setQueryStates({ epciGroupName: null, epciGroupNameAuto: null })
      return
    }

    setQueryStates({ epciGroupName: proposedName, epciGroupNameAuto: '1' })
  }, [urbanismeDoc, territoryLabel, proposedName, isAutoGenerated, epciGroupName, setQueryStates])
}
