'use client'

import { parseAsArrayOf, parseAsString, useQueryStates } from 'nuqs'
import { useEffect } from 'react'
import { useDocurbaEpcis } from '~/hooks/use-docurba-epcis'
import { buildEpciGroupName } from '~/utils/epci-group-name'

type UseEpciGroupNamePrefillArgs = {
  /** Libellé du territoire, construit par `buildTerritoryLabel`. Vide tant que l'EPCI de base n'est pas connu. */
  territoryLabel: string
}

/**
 * Propose un nom de groupe dérivé du territoire et, si l'utilisateur travaille sur un document
 * d'urbanisme, du document trouvé sur Docurba pour l'EPCI de base.
 *
 * Le nom proposé n'écrase jamais une saisie manuelle : `epciGroupNameAuto` marque dans l'URL que la
 * valeur courante a été générée. Passer par l'URL plutôt que par une ref permet de survivre au retour
 * depuis l'étape suivante, qui démonte le composant.
 */
export const useEpciGroupNamePrefill = ({ territoryLabel }: UseEpciGroupNamePrefillArgs) => {
  const [{ baseEpci, epcis, epciGroupName, epciGroupNameAuto, urbanismeDoc }, setQueryStates] = useQueryStates({
    baseEpci: parseAsString,
    epcis: parseAsArrayOf(parseAsString).withDefault([]),
    epciGroupName: parseAsString,
    epciGroupNameAuto: parseAsString,
    urbanismeDoc: parseAsString,
  })

  // La liste complète (et non `[baseEpci]`) pour partager la queryKey du ScotInfoTable du drawer et n'émettre qu'une requête.
  const { data: docurbaByEpci } = useDocurbaEpcis(epcis)
  const docurba = baseEpci ? docurbaByEpci?.[baseEpci] : null

  const isAutoGenerated = !epciGroupName || epciGroupNameAuto === '1'
  const proposedName = territoryLabel ? buildEpciGroupName({ docurba, territoryLabel, worksOnUrbanismeDoc: urbanismeDoc === 'oui' }) : ''

  useEffect(() => {
    if (!urbanismeDoc || !proposedName) return
    if (!isAutoGenerated) return
    if (proposedName === epciGroupName) return

    setQueryStates({ epciGroupName: proposedName, epciGroupNameAuto: '1' })
  }, [urbanismeDoc, proposedName, isAutoGenerated, epciGroupName, setQueryStates])
}
