ALTER TYPE "UserType" ADD VALUE IF NOT EXISTS 'Admin';
ALTER TYPE "UserType" ADD VALUE IF NOT EXISTS 'AgenceDepartementale';
ALTER TYPE "UserType" ADD VALUE IF NOT EXISTS 'BailleurSocialAgencePrivee';
ALTER TYPE "UserType" ADD VALUE IF NOT EXISTS 'Commune';
ALTER TYPE "UserType" ADD VALUE IF NOT EXISTS 'EPCI';
ALTER TYPE "UserType" ADD VALUE IF NOT EXISTS 'OperateurRayonnementRegional';
ALTER TYPE "UserType" ADD VALUE IF NOT EXISTS 'SCOTPETR';
